/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include <cate_bloom.h>
/* Header for class CateBloomJni */

#ifndef _Included_CateBloomJni
#define _Included_CateBloomJni
#ifdef __cplusplus
extern "C" {
#endif

    JNIEXPORT jlong JNICALL Java_com_cooeeui_brand_zenlauncher_unittest_category_CateBloomJni_initpath
        (JNIEnv *env, jobject obj, jstring jblock_path){
        const char* block_path = (*env)->GetStringUTFChars(env, jblock_path, 0);
        return (jlong) cate_bloom_init((char *)block_path);
    }

    JNIEXPORT jlong JNICALL Java_com_cooeeui_brand_zenlauncher_unittest_category_CateBloomJni_initbytes
        (JNIEnv *env, jobject obj, jbyteArray input, jint numBytes){
            jbyte* bufferPtr = (*env)->GetByteArrayElements(env, input, NULL);
            char *inputBytes = malloc(numBytes * sizeof(char));
            memcpy(inputBytes, bufferPtr, numBytes);
            (*env)->ReleaseByteArrayElements(env, input, bufferPtr, 0);
        return (jlong) inputBytes;
    }

    JNIEXPORT jint JNICALL Java_com_cooeeui_brand_zenlauncher_unittest_category_CateBloomJni_pname2caid
        (JNIEnv *env, jobject obj, jlong jblocks, jstring jpname){
            const char* pname = (*env)->GetStringUTFChars(env, jpname, 0);
            return (jint) cate_bloom_caid((long) jblocks, (char *)pname);
        }

    JNIEXPORT void JNICALL Java_com_cooeeui_brand_zenlauncher_unittest_category_CateBloomJni_free
        (JNIEnv *env , jobject obj, jlong jblocks){
            cate_bloom_free((long) jblocks);
        }

#ifdef __cplusplus
}
#endif
#endif
