/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cooeeui_brand_zenlauncher_unittest_category_CateBloomJni */

#ifndef _Included_com_cooeeui_brand_zenlauncher_unittest_category_CateBloomJni
#define _Included_com_cooeeui_brand_zenlauncher_unittest_category_CateBloomJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cooeeui_brand_zenlauncher_unittest_category_CateBloomJni
 * Method:    initpath
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_cooeeui_brand_zenlauncher_unittest_category_CateBloomJni_initpath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_cooeeui_brand_zenlauncher_unittest_category_CateBloomJni
 * Method:    initbytes
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_com_cooeeui_brand_zenlauncher_unittest_category_CateBloomJni_initbytes
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_cooeeui_brand_zenlauncher_unittest_category_CateBloomJni
 * Method:    pname2caid
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cooeeui_brand_zenlauncher_unittest_category_CateBloomJni_pname2caid
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_cooeeui_brand_zenlauncher_unittest_category_CateBloomJni
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_cooeeui_brand_zenlauncher_unittest_category_CateBloomJni_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
